  
name: matrix-test-action
on: 
  workflow_dispatch:
jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ["eastus.json","westus.json"]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Azure Login
       uses: Azure/login@v1.1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
     - name: Test matrix
       run: echo "Value $REGION"
       env:
         REGION: ${{ matrix.region }}
