  
name: matrix-test-action
on: 
  workflow_dispatch:
jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ["eastus","westus"]
    steps:
      - name: Test matrix
        run: echo "Value $REGION"
        env:
          REGION: ${{ matrix.region }}
